name: novelsolutely
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_tags: ^0.4.8+2
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  path_provider: ^1.6.14
  uuid: ^2.2.2
  string_validator: ^0.1.4
  flutter:
    sdk: flutter


dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Ribeye
      fonts:
        - asset: assets/fonts/Ribeye-Regular.ttf
